### PR TITLE
Add ability to add nodes to cluster, fix windows support and run linux kitchen tests through docker

### PR DESCRIPTION
**Pull request by mwrock**
I forked this cookbook to illustrate how one might use test-kitchen to perform multi-node testing. See http://www.hurryupandwait.io/blog/multi-node-testing-with-test-kitchen-and-docker. I made several changes that I'd like to submit back. The changes are included in this PR however I assume you would prefer this PR to be broken up. Thats totally cool but I thought I'd at least submit this initial PR to see if there was general interest.

Here is what is included:
- Compatibility with docker. I eliminated the check for the listening port using `netstat` since many docker base images do not include net tools. I think this check is unnecessary anyways considering that an HTTP check is later performed.
- Changed `.kitchen.yml` to use docker for all linux platforms
- Added a `join` action to the cluster resource so that one may add nodes to a cluster.
- Fixed windows community server converges. I'm guessing that this recipe has not been updated in a while and has grown stale. I had to make a number of tweaks in order to get windows to converge and add firewall rules to get it to play nice with adding other nodes. I also converted the minitest handler server test to serverspec since I simply could not get those tests to behave in windows.

Might be a couple weeks before I get time to send propper PRs but I have fixed up all unit tests and added tests here where appropriate and I have also added Kitchen tests to cover multinode scenarios.

Please feel free to comment if there are items you'd rather not take. For example maybe you want to keep everything testing in vagrant.

Thanks!

### CODE REVIEW

**Comment by juliandunn** [comment]
Hey @mwrock -- this is great. I don't use Couchbase anymore (Chef doesn't use it) but I'm happy to take the contribution as others might find it useful.

I'd definitely like to see this PR broken up into features and if we could leave testing as Vagrant, that would be the lowest common denominator for everyone. The `join` action is something folks have been asking for for a while, so I think that's the most valuable & where I'd start.

**Comment by mwrock** [comment]
Awesome. Will send this stuff on once I get some cycles.

**Comment by nickm4062** [comment]
@juliandunn sentiment seconded

**Comment by alisade** [comment]
+1

**Comment by nraboy** [comment]
Was wondering the status on this?

**Comment by chrisputonen** [comment]
This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.
Conflicting files
.gitignore
.kitchen.yml
attributes/server.rb
files/default/test/server_test.rb
libraries/client.rb
recipes/server.rb
templates/default/setup.iss.erb

**Pull request closed without merging**
